[package]
name = "test-fungible-token"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]



[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
