[package]
name = "moloch"
version = "0.1.0"
authors = ["Alexander Keating <keating.dev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigint = "4.4.3"
near-sdk = "3.0.1"
